### ISSUE TITLE
Страница "история театра"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#11]
В макетах называется ["о театре"](https://www.figma.com/file/xockMwJFRcDaGT5c9B0nmO/Luna-Main?node-id=113%3A923&t=Cop6H7NP6P2nbyNQ-0)

**ToDo**:
  - [x] верстка: десктопная версия 
  - [x] верстка: мобильная версия
  - [x] анимация при наведении на картинки как тут [new.lunatheatre.ru/plays](http://new.lunatheatre.ru/plays) https://github.com/tribble-io/luna/blob/24bd0fe2c27df2ba2993e531b7942cf8ceaa2f32/src/components/showsCards/shows.module.scss#L91
  - [x] в разделе архивные фотографии: использовать этот компонент https://github.com/tribble-io/luna/tree/main/src/components/photoSlider

**Comment by demig00d** [comment]
- [ ] 2 блока немного не так сделаны (1 скрин)
- [ ] писала про то, что в блоке текст нужно подправить, как в макете (2 скрин)
- [ ] тоже писала, что блок немного не как в макете (3 скрин) + после этого блока след блок идет на меньшем расстоянии, чем нужно (все в макете)
- [ ] тоже писала, что нужно в тексте «от» перенести на след строчку (:  (4 скрин)
- [ ] в последнем абзаце «гознак» нужно тоже перенести на след строчку (5 скрин)
- [ ] вроде утвердили, что с обычных фото нужно убрать анимацию зума при наведении
- [ ] галерея просто супер! нужно только левую стрелку сделать по цвету неактивной, если лента не бесконечно во все стороны листается (есть в макете)
